services:
  app:
    build: .
    container_name: challengeApp
    restart: always
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      TZ: America/Sao_Paulo
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}'
    networks:
      - challenge-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: challengeDatabase
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - challenge-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:

networks:
  challenge-network: