services:
  app:
    container_name: challengeApp_dev
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    user: root
    networks:
      - challenge-network

  db:
    container_name: challengeDatabase_dev
    ports:
      - '${DB_PORT}:5432'
    networks:
      - challenge-network

networks:
  challenge-network: