apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: devops-lab-secrets
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    DATABASE_URL: {{ .Values.envs.DATABASE_URL }}
    DB_PORT: {{ .Values.envs.DB_PORT }}
    JWT_SECRET: {{ .Values.envs.JWT_SECRET }}
    JWT_REFRESH_SECRET: {{ .Values.envs.JWT_REFRESH_SECRET }}
    POSTGRES_DB: {{ .Values.envs.POSTGRES_DB }}
    POSTGRES_PASSWORD: {{ .Values.envs.POSTGRES_PASSWORD }}
    POSTGRES_USER: {{ .Values.envs.POSTGRES_USER }}
    
  template:
    metadata:
      name: devops-lab-secrets
      namespace: {{ .Release.Namespace }}
