apiVersion: v1
data:
  APP_PORT: MzAwMA==
  DATABASE_URL: cG9zdGdyZXNxbDovL2RvY2tlcjpzZWNyZXRAcG9zdGdyZXMtcG9zdGdyZXNxbDo1NDMyL2RiX2Rldj9zY2hlbWE9cHVibGlj
  DB_PORT: NTQzMg==
  JWT_REFRESH_SECRET: UmVmcmVzaFNlZ3JlZG9NYXhpbW8xMjM=
  JWT_SECRET: U2VncmVkb01heGltbzEyMw==
  POSTGRES_DB: ZGJfZGV2
  POSTGRES_PASSWORD: c2VjcmV0
  POSTGRES_USER: ZG9ja2Vy
kind: Secret
metadata:
  name: devops-lab-secrets
